config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("django.contrib.auth.urls")),
    path("users/", include("jagazone.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

jagazone/users/urls.py
from django.urls import path
from jagazone.users import views


app_name = "users"
urlpatterns = [
    # path("~redirect/", view=views.user_redirect_view, name="redirect"),
    path("register/", view=views.user_register_view, name='register'),
    path("create/", view=views.user_create_view, name="create"),
    path("<uuid:pk>/", view=views.user_detail_view, name="detail"),
    path("update/<uuid:pk>/", view=views.user_update_view, name="update"),
    path("delete/<uuid:pk>/", view=views.user_delete_view, name="delete"),
    path("", view=views.user_list_view, name="user-list")

]

jagazone/users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.utils import timezone
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models


class User(AbstractUser):
    """
    Default custom user model for Jagazone.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore


    class Meta:
        ordering = ('name',)
        get_latest_by = 'name'

    def __str__(self) -> str:
        return f'<User ID: {self.id}>'

    @property
    def user_profile(self):
        return self.usersprofile

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})


class Gender(models.TextChoices):
        male = 'Male'
        female = 'Female'
        other = 'Other'


class UsersProfile(models.Model):
    GUEST = 'GU'
    ADMIN = 'AD'
    N_CONFIRMED = 'NU'
    CONFIRMED = 'CU'

    ROLE_CHOICES = [
        (GUEST, 'Gues'),
        (ADMIN, 'Admin'),
        (N_CONFIRMED, 'Not confirmed user'),
        (CONFIRMED, 'Confirmed User'),
    ]

    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField(blank=True)
    role = CharField(max_length=2,
                    choices=ROLE_CHOICES,
                    default='GU',
                    )
    gender = CharField(max_length=15,
                        choices=Gender.choices,
                        default=Gender.other.other,
                        )
    created = models.DateTimeField(auto_now_add=True)
    archived = models.DateTimeField(blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)
    phone_number = models.CharField(max_length=25, blank=True)
    confirmed = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)
        get_latest_by = 'created'

    def __str__(self) -> str:
        return f'<UserProfile ID: {self.id}>'

    def age(self):
        if self.birthdate:
            return timezone.now().year - self.birthdate.year

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

jagazone/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import UsersProfile

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(admin_forms.UserCreationForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(admin_forms.UserChangeForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class UserForm(forms.ModelForm):
    edit_user = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    class Meta:
        model = User
        fields = ["username", "email", "password"]


class DeleteUserForm(forms.Form):
    delete_user = forms.BooleanField(widget=forms.HiddenInput, initial=True)


class UserProfileForm(forms.ModelForm):
    edit_user_profile = forms.BooleanField(widget=forms.HiddenInput, initial=True)

    class Meta:
        model = UsersProfile
        fields = ["birthdate", "role", "gender", "phone_number"]


class DeleteUserProfileForm(forms.Form):
    delete_user_profile = forms.BooleanField(widget=forms.HiddenInput, initial=True)

jagazone/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

jagazone/users/views.py
import uuid

from django.contrib.auth import get_user_model, forms
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods, require_GET
from django.utils.translation import gettext_lazy as _
from .models import UsersProfile
from .forms import UserProfileForm, UserForm, DeleteUserForm


User = get_user_model()


@require_http_methods(("GET", "POST"))
def user_register_view(request):
    register_form = forms.UserCreationForm(request.POST or None)
    if request.method == 'POST':
        if register_form.is_valid():
            register_form.save()

            return HttpResponseRedirect(reverse_lazy("login"))
    context = {
        'register_form':register_form,
    }
    return render(request, "users/register.html", context)


@require_GET
def user_detail_view(request, pk):
    user = get_object_or_404(User, id=pk)

    context = {
      "user": user
    }
    return render(request, "users/user_detail.html", context)


@require_GET
def user_list_view(request):
    users_list = User.objects.all()
    paginate_by = 10
    paginate_class = Paginator(users_list, paginate_by)
    page_number = request.GET.get('page')
    page_class = paginate_class.page(page_number or 1)

    context = {
        'users_list': users_list,
        'paginate': paginate_class,
        'page': page_class,
    }
    return render(request, 'users/user_list.html', context=context)


@require_http_methods(("GET", "POST"))
def user_save(user_form, user_profile_form):
    user = user_form.save()
    print(user_form.cleaned_data.get('password'))
    if user_form.cleaned_data.get('password'):
        user.set_password(user_form.cleaned_data['password'])
        user.save(update_fields=['password'])
    user_profile = user_profile_form.save(commit=False)
    user_profile.user = user
    user_profile.save()
    return user


@require_http_methods(("GET", "POST"))
def user_create_view(request):
    user_form = UserForm(request.POST or None)
    user_profile_form = UserProfileForm(request.POST or None)
    if request.method == 'POST':
        if user_form.is_valid() and user_profile_form.is_valid():
            user_save(user_form, user_profile_form)
            return HttpResponseRedirect(reverse_lazy("users:user-list"))

    context = {
        'user_form': user_form,
        'user_profile_form': user_profile_form,
    }
    return render(request, 'users/user_form.html', context=context)


@require_http_methods(("GET", "POST"))
def user_delete_view(request, pk):
    user = get_object_or_404(User, id=pk)
    user_profile = get_object_or_404(UsersProfile, user_id=pk)
    delete_user = DeleteUserForm(request.POST or None)
    if request.method == "POST" and 'user_delete':
        user_profile.delete()
        user.delete()
        return HttpResponseRedirect(reverse_lazy("users:user-list"))

    context = {
        'delete_user': delete_user,
        }

    return render(request, 'users/user_delete.html', context=context)


@require_http_methods(("GET", "POST"))
def user_update_view(request, pk):
    user = get_object_or_404(User.objects.select_related('auth_token'), id=pk)
    user_profile = get_object_or_404(UsersProfile.objects.select_related('user'), user_id=pk)
    edit_user = UserForm(instance=user)
    edit_user_profile = UserProfileForm(instance=user_profile)
    if request.method == 'POST':
        if 'edit_user' in request.POST and 'edit_user_profile' in request.POST:
            edit_user_profile = UserProfileForm(request.POST, instance=user_profile)
            edit_user = UserForm(request.POST, instance=user)
            if edit_user.is_valid() and edit_user_profile.is_valid():
                if edit_user.cleaned_data.get('password'):
                    user.set_password(edit_user.cleaned_data['password'])
                edit_user.save()
                edit_user_profile.save()

                return HttpResponseRedirect(reverse_lazy("users:user-list"))


    context = {
        'edit_user_profile': edit_user_profile,
        'edit_user': edit_user,
    }
    return render(request, 'users/user_form.html', context=context)

jagazone/templates/users/login.html
{% extends "base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "Login"%}
{% endblock %
{% block content %}
    <form method="post"
    action="{% url 'home' %}"
      >
      {% csrf_token %}
      {{ form|crispy}}
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

jagazone/templates/users/logout.html
{% extends "base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "Logout"%}
{% endblock %
{% block content %}
  {%if user.is_autenticated%}
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary"> You shure? </button>
    </form>
  {% endif %}
{% endblock %}

jagazone/templates/users/register.html
{% extends "base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "Register"%}
{% endblock title %}
{% block content %}
    <form method="post"
          >
      {% csrf_token %}
      {{ register_form|crispy }}

      <button type="submit" class="btn btn-primary">Register >></button>
    </form>
{% endblock content %}

jagazone/templates/users/user_delete.html
{% extends "base.html" %}
{% load i18n%}

{% block content %}
    <p>{% blocktranslate %}
      <br>
      <br>
      <b>Are you sure you want to delete the account?

      <p>All of the following related items will be deleted:</p></b>
      {% endblocktranslate %}</p>
    <br>
      <br>
    <form method="post">{% csrf_token %}
    <div>
      {{ delete_user }}
    <input type="hidden" name="post" value="yes">
    <input type="submit" class="btn btn-danger" value="{% translate 'Yes, I’m sure' %}">
    <a href="#" class="btn btn-warning">{% translate "No, take me back" %}</a>
    </div>
    </form>
{% endblock content %}

jagazone/templates/users/user_detail.html
{% extends "base.html" %}

{% load static %}
{% block title %}
  User:
    {{ user.username }}

{% endblock title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>


          {{ user.username }}

      </h2>
      {% if user.name %}
        <p>{{ user.name }}</p>
      {% endif %}
    </div>
  </div>
    <!-- Action buttons -->
    <div class="row">
      <div class="col-sm-12">
        <a class="btn btn-primary" href="{% url 'users:update' user.pk %}" role="button">My Info</a>
        <a class="btn btn-primary"
           href="{% url 'account_email' %}"
           role="button">E-Mail</a>
        <!-- Your Stuff: Custom user template urls -->
      </div>
    </div>
    <!-- End Action buttons -->

</div>
{% endblock content %}

jagazone/templates/users/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags i18n %}

{% block title %}

{% if request.path == '/users/create/'%}
  {% trans 'Add User' %}
{% else %}
  {{ name }}
{% endif %}

{% endblock title %}
{% block content %}
    {% if request.path == '/users/create/'%}
      <h2>Add User</h2>
      <form method="post"
      action= "{% url 'users:create' %}"
           >
      {{ user_form |crispy}}
      {{ user_profile_form |crispy }}
      {% csrf_token %}
          <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn btn-primary">Add</button>
            </div>
          </div>
      </form>
    {%else%}
      <hr>
      <h2>Edit User</h2>
      <form method="post"
            {% if object %}
              action="{% url 'users:update' user.pk %}"
            {% endif %}
              >
          {% csrf_token %}
          {{ edit_user|crispy }}
          {{ edit_user_profile|crispy }}
          <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
      </form>
      <hr>
    {%endif%}
{% endblock content %}

jagazone/templates/users/user_list.html
{% extends "base.html" %}

{% load static i18n %}

{% block title %}
  {% trans 'User List'%} |
  {{ block.super }}
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="d-grid gap-2 d-flex justify-content-between">
        <h2>
          {% trans 'User List'%}
      </h2>
      <div>
      <a href="{% url 'users:create' %}" class="btn btn-primary">Add</a>
    </div>
      </div>
    </div>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">{% trans 'Name'%}</th>
            <th scope="col">{% trans 'User'%}</th>
            <th scope="col">{% trans 'Email'%}</th>
            <th scope="col">{% trans 'Actions'%}</th>
          </tr>
        </thead>
        <tbody>
          {% for user in page.object_list %}
            {%  if user.is_staff != True %}
              <tr>
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ user.name }}</td>
                <td><a href= "{% url 'users:detail' user.pk %}">{{ user.username }}</a></td>
                <td>{{ user.email }}</td>
                <td><a href="{% url 'users:update' user.pk %}" class="btn btn-success">Edit</a></td>
                <td><a href="{% url 'users:delete' user.pk %}" class="btn btn-danger">Delete</a></td>
              </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if paginate.num_pages > 1 %}
    <div class="row">
      <nav aria-label="Page navigation example ">
        <ul class="pagination">
          {% if page.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
          </li>
            {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
          </li>
            {% endif %}
          {% for number in paginate.page_range %}
          <li class="page-item {% if number == page.number %}active{%endif%}"><a class="page-link" href="?page={{ number }}">{{ number }}</a></li>
          {% endfor %}
          {% if page.has_next %}
          <li class="page-item">

            <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>

          </li>
          {% else %}
          <li class="page-item disabled">

            <a class="page-link"  href="#">Next</a>

          </li>

            {% endif %}
        </ul>
      </nav>
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}